site_name: CDCR EIS AWS Documentation
site_url: https://awsdocs.cdcr.ca.gov/
theme:
  name: material
  language: en
  logo: site_assets/logo.png
  favicon: site_assets/favicon.ico
  features:
    - navigation.instant
    #- navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    #- navigation.expand
    #- navigation.path
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - navigation.top
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
extra:
  generator: false
extra_css:
  - site_assets/extra.css
extra_javascript:
  - https://unpkg.com/mermaid@11.4.0/dist/mermaid.min.js
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - tables
  - pymdownx.critic
  - pymdownx.details
  - toc:
      anchorlink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format